apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ecart
  name: ecart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecart
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ecart
    spec:
      containers:
      - image: dheeraj7444/shopping-cart:1
        name: shopping-cart
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ecart
  name: ecart
spec:
  ports:
  - port: 8070
    protocol: TCP
    targetPort: 8070
  selector:
    app: ecart
  type: NodePort
status:
  loadBalancer: {}
